# Generated by Django 2.2.3 on 2019-08-10 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite_key',
            field=models.CharField(default='none', max_length=256),
        ),
        migrations.AlterField(
            model_name='invitekey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_keys', to=settings.AUTH_USER_MODEL),
        ),
    ]
